# Generated by Django 4.1.2 on 2022-12-31 01:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('status', models.CharField(choices=[('top-featured', 'Top Featured'), ('best-seller', 'Best Seller')], max_length=45, null=True)),
                ('type', models.CharField(choices=[('Sale', 'Sale'), ('New', 'New')], max_length=45, null=True)),
                ('data_added', models.DateField(default=datetime.datetime(2022, 12, 31, 3, 30, 12, 866183))),
                ('quantity', models.IntegerField(null=True)),
                ('description', models.TextField(default="The dress' waist is narrow, but it's a tight fit. A large belt helps accentuate her waist in a stylish manner.\nBelow the waist the dress widens and has multiple symmetric layers towards the bottom. The dress reaches to just below her knees and is slightly longer at the sides.\n")),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home_app.category')),
                ('size', models.ManyToManyField(to='home_app.size')),
            ],
        ),
    ]
