# Generated by Django 4.1.2 on 2022-12-31 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_added',
            field=models.DateField(default=datetime.datetime(2022, 12, 31, 3, 30, 19, 302969)),
        ),
    ]
