# Generated by Django 4.1.2 on 2022-12-30 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_added',
            field=models.DateField(default=datetime.datetime(2022, 12, 30, 2, 33, 36, 657655)),
        ),
    ]
